name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: ianwalter/puppeteer@v2.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        export DISPLAY=:99.0
        sh -e /etc/init.d/xvfb start
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
